# Generated by Django 4.0.5 on 2022-06-08 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ServerApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityWriting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('format_of_writing', models.IntegerField(choices=[(1, 'Free writing'), (2, 'Suggestion'), (3, 'Notice')])),
                ('post', models.TextField(blank=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='post_author', to='ServerApi.studentuser')),
                ('post_likes', models.ManyToManyField(to='ServerApi.studentuser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
